while not game:IsLoaded() do
    wait()
end
local libary = loadstring(game:HttpGet("https://pastebin.com/raw/RvJ0qewm", true))()
local main = libary:CreateWindow("STS")


local mod = main:Button("Draw001", function()
_G.Draw001_enabled = not _G.Draw001_enabled

while _G.Draw001_enabled do
local args = {
    [1] = "Hatch",
    [2] = "Draw001",
    [3] = {}
}

game:GetService("ReplicatedStorage").Events.Pets.Re_Draw:FireServer(unpack(args))

wait(0.1)
end
end)

local mod = main:Button("Draw002", function()
_G.Draw002_enabled = not _G.Draw002_enabled

while _G.Draw002_enabled do
local args = {
    [1] = "Hatch",
    [2] = "Draw002",
    [3] = {}
}

game:GetService("ReplicatedStorage").Events.Pets.Re_Draw:FireServer(unpack(args))

wait(0.1)
end
end)

local mod = main:Button("Draw003", function()
_G.Draw003_enabled = not _G.Draw003_enabled

while _G.Draw003_enabled do
local args = {
    [1] = "Hatch",
    [2] = "Draw003",
    [3] = {}
}

game:GetService("ReplicatedStorage").Events.Pets.Re_Draw:FireServer(unpack(args))

wait(0.1)
end
end)

local mod = main:Button("HeroAttack", function()
_G.HeroAttack_enabled = not _G.HeroAttack_enabled

while _G.HeroAttack_enabled do
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = workspace.UserPets:FindFirstChild("3952043826"):FindFirstChild("Pom-Pom")
}

game:GetService("ReplicatedStorage").Events.Hero.HeroAttack:FireServer(unpack(args))

wait(0.01)
end
end)

