while not game:IsLoaded() do
    wait()
end
local libary = loadstring(game:HttpGet("https://pastebin.com/raw/RvJ0qewm", true))()
local main = libary:CreateWindow("STS")

local mod = main:Button("ClickDamage", function()
_G.kClickDamage_enabled = not _G.ClickDamage_enabled

while _G.ClickDamage_enabled do
game:GetService("ReplicatedStorage").Events.Fight.ClickDamage:FireServer()

wait(0.1)
end
end)

local mod = main:Button("Draw001", function()
_G.Draw001_enabled = not _G.Draw001_enabled

while _G.Draw001_enabled do
local args = {
    [1] = "Hatch",
    [2] = "Draw001",
    [3] = {}
}

game:GetService("ReplicatedStorage").Events.Pets.Re_Draw:FireServer(unpack(args))

wait(0.1)
end
end)

local mod = main:Button("UPG", function()
_G.UPG_leave_enabled = not _G.UPG_leave_enabled

while _G.UPG_leave_enabled do
-- Script generated by SimpleSpy - credits to exx#9394

game:GetService("ReplicatedStorage").Events.SendRebirthRequest:FireServer()

wait(0.1)
end
end)

